### ISSUE TITLE
GRUB fails to detect ZFS filesystem

### ISSUE THREAD

**Issue by woodypl** [zfsonlinux/pkg-zfs#73]
Hi,
I have created a RAIDZ-2 ZFS pool using your guide at https://github.com/dajhorn/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem as a base.
The pool was created with the following command:
`zpool create -o ashift=12 rpool raidz2 disk1 disk2 disk3 disk4` (where diskN correspond to /dev/disk/by-id entries).

Grub-probe is failing to detect the filesystem, though - I have checked both form outside and inside the chroot. The log is here: https://gist.github.com/4551538

Following this, I also tried Grub 2.00's grub-probe. It would not work either, with slightly different output: https://gist.github.com/4551533

Is there anything wrong I'm doing here? Does the Grub version from the PPA support ashift=12?

**Comment by dajhorn** [comment]
> Is there anything wrong I'm doing here?

No.

> Does the Grub version from the PPA support ashift=12?

No, that is the problem here.  These are the pertinent lines in the log file:

```
grub-core/fs/zfs/zfs.c:3072: incorrect nvlist header
grub-core/kern/fs.c:77: zfs detection failed.
```

This should be fixed for the Raring build series.

**Comment by woodypl** [comment]
Many thanks for your extremely fast reply!
I have also tried building Grub-1.99 using the sources from your PPA, but applying ZFS support from here, allegedly with working ashift=12 :
https://github.com/pendor/grub-zfs/commit/e7b6ef3ac3b9685ac4c394c897b1d4221b7381f1

However, this still won't work:

```
grub-core/fs/zfs/zfs.c:2080: reading label 0 at sector 0 (byte 0)
grub-core/fs/zfs/zfs.c:2088: error checking label 0
grub-core/fs/zfs/zfs.c:2080: reading label 1 at sector 512 (byte 262144)
grub-core/fs/zfs/zfs.c:2088: error checking label 1
grub-core/fs/zfs/zfs.c:2080: reading label 2 at sector 3900660736 (byte 1997138296832)
grub-core/fs/zfs/zfs.c:2088: error checking label 2
grub-core/fs/zfs/zfs.c:2080: reading label 3 at sector 3900661248 (byte 1997138558976)
grub-core/fs/zfs/zfs.c:2088: error checking label 3
```

Just for the record, I had GRUB 2.00 working on Gentoo with ashift=12 before. Using grub2-probe binary from that system on this pool still results in same errors as above. This might be out of scope of this issue, but I really wonder why this might be the case.

**Comment by dajhorn** [comment]
> Many thanks for your extremely fast reply!

Welcome.

> I have also tried building Grub-1.99 using the sources from your PPA, but applying ZFS support from here, allegedly with working ashift=12 : pendor/grub-zfs@e7b6ef3

Upstream rewrote most of the pertinent code in a way that does the same thing as that patch branch.  It would be easier to import a post grub-2.00 release than to reapply that patch branch to anything in the grub-1.99 series.

> Just for the record, I had GRUB 2.00 working on Gentoo with ashift=12 before. Using grub2-probe binary from that system on this pool still results in same errors as above. This might be out of scope of this issue, but I really wonder why this might be the case.

Note that those utilities use libraries that affect the result.

Debian carries a large patch queue on top of older upstream grub sources and is far behind Gentoo.  To get `ashift=12` working, you need to rediff everything and double-check for Ubuntu weirdness.

This is a non-trivial amount of work, but if you do it, then please let me know.

**Comment by woodypl** [comment]
> Note that those utilities use libraries that affect the result.

That's true... At some point in time I even copied over all ZFS-related libraries and loaded them by setting LD_LIBRARY_PATH, but the results were still like here: https://gist.github.com/4551533
Maybe I should have copied all the libraries, on the other hand it seems unlikely to me that they are affecting the probe result.

> This is a non-trivial amount of work, but if you do it, then please let me know.

I would love to get this to work - however I'm just afraid it's not only `ashift=12` that causes the problem. If I have time to spend on that, I will try.

**Comment by woodypl** [comment]
And it seems I was right...
I started playing around - first created a new pool, consisting of one disk, without `ashift` option. Then another one, with `ashift=9`. I was still getting exactly same results as in my initial post.
Then I changed the ZFS PPA from daily to stable... and was no longer able to import my pool:
`cannot import 'testpool': pool is formatted using a newer ZFS version`
Then I noticed this:
`[   80.210452] ZFS: Loaded module v0.6.0.92-rc13, ZFS pool version 5000, ZFS filesystem version 5`
Well - my fault, I guess I should have noticed that. However, weren't previous daily releases using zpool version 28 (even your guide seems to suggest that)?

Then I created a new pool - it seems that the GRUB 1.99 package from your PPA supports `ashift=12` after all (at least for grub-probe):

```
root@ubuntu:/# zpool get all testpool|grep ashift
testpool  ashift         12                      local
root@ubuntu:/# grub-probe /
zfs
```

I wonder what changes were made in the daily package that cause both GRUB 1.99 and 2.00 to fail to detect the filesystem. Anyway, my problem is resolved for now - thanks for your help!

**Comment by woodypl** [comment]
And to answer my own question:
The changes are here: https://launchpad.net/~zfs-native/+archive/daily/+files/zfs-linux_0.6.0.91-0ubuntu1~precise1_0.6.0.92-0ubuntu1~precise1.diff.gz

Funny enough, `include/sys/fs/zfs.h` contains the following quote:

```
When bumping up SPA_VERSION, make sure GRUB ZFS understands the on-disk
 * format change.
```
